export const products = [
  {
    image: "/uploads/products/banner1.jpg",
    category: "product",
  },
  {
    image: "/uploads/products/banner2.jpg",
    category: "product",
  },
  {
    image: "/uploads/products/banner3.jpg",
    category: "product",
  },
  {
    image: "/uploads/products/kabab.png",
    category: "singleBanner",
  },
  {
    image: "/uploads/products/burger.webp",
    images: [
      "/uploads/products/burger.webp",
      "/uploads/products/pizza1.jpg",
      "/uploads/products/pizza2.jpg",
      "/uploads/products/pizza3.jpg",
    ],
    description: "صحن مشاوي مشكل مع سرفيس كامل وبسعر مناسب",
    category: "swiper",
  },
  {
    image: "/uploads/products/fakharFood.png",
    images: [
      "/uploads/products/fakharFood.png",
      "/uploads/products/pizza1.jpg",
      "/uploads/products/pizza2.jpg",
      "/uploads/products/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "/uploads/products/fish.jpg",
    images: [
      "/uploads/products/fish.jpg",
      "/uploads/products/grill1.jpg",
      "/uploads/products/pizza2.jpg",
      "/uploads/products/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "/uploads/products/sea-food.jpg",
    images: [
      "/uploads/products/sea-food.jpg",
      "/uploads/products/grill1.jpg",
      "/uploads/products/pizza2.jpg",
      "/uploads/products/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "/uploads/products/mixFood.webp",
    images: [
      "/uploads/products/mixFood.webp",
      "/uploads/products/pizza1.jpg",
      "/uploads/products/pizza2.jpg",
      "/uploads/products/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "/uploads/products/specialPlates1.webp",
    title: "بيتزا 1",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza1",
  },
  {
    image: "/uploads/products/specialPlates2.webp",
    title: "بيتزا 2",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza2",
  },
  {
    image: "/uploads/products/specialPlates3.webp",
    title: "بيتزا 3",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza3",
  },
  {
    image: "/uploads/products/specialPlates4.webp",
    title: "بيتزا 4",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza4",
  },
  {
    image: "/uploads/products/specialPlates5.webp",
    title: "بيتزا 5",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza4",
  },
  {
    image: "/uploads/products/specialPlates6.webp",
    title: "بيتزا 6",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "special_plates",
    caros: "pizza4",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/grillFood.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/ham.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/seafood.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    icon: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "/uploads/products/dessert1.jpg",
    title: "كنافة",
    description: "كنافة على الفحم:\n طريقة عمل الكنافة...",
    price: 90,
    discount: 20,
    category: "dessert",
    hasRadius: true,
  },
  {
    image: "/uploads/products/dessert2.jpg",
    title: "حلاوة الجبن",
    description: "كنافة على الفحم:\n طريقة عمل الكنافة...",
    price: 90,
    discount: 20,
    category: "dessert",
  },
  {
    image: "/uploads/products/dessert3.jpg",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 20,
    category: "dessert",
  },
  {
    image: "/uploads/products/dessert4.webp",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 20,
    category: "dessert",
  },
  {
    image: "/uploads/products/offerM1.webp",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 10,
    category: "offer",
  },
  {
    image: "/uploads/products/offerM2.webp",
    title: "حلاوة الجبن",
    description: "كنافة على الفحم:\n طريقة عمل الكنافة...",
    price: 90,
    discount: 15,
    category: "offer",
  },
  {
    image: "/uploads/products/offerM3.webp",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 12,
    category: "offer",
  },
  {
    image: "/uploads/products/offerM4.avif",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 5,
    category: "offer",
  },
  {
    image: "/uploads/products/offerM5.webp",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 10,
    category: "offer",
  },
];
